name: mongo/Update-Replicaset-Attributes

run-name: mongo/Update-Replicaset-Attributes-for-${{ inputs.StackName }}-${{ github.run_number }}

on:
  workflow_dispatch:
    inputs:
      StackName:
        type: choice
        description: CloudFormation stack name of the Mongo replica set
        options:
          - Mongo-Stack-1
          - Mongo-Stack-2

      AmiId:
        type: string
        default: ""
        description: AMI ID

      InstanceType:
        type: string
        default: ""
        description: Instance Type

jobs:
  setup-job-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Generate github token
        run: |
          echo "A GitHub app installation token was generated for cloning repositories."
          echo "The GitHub action, such as tibdex/github-app-token, can be used for the same purpose."

      - name: Checkout Cloudformation repo
        run: |
          echo "Checkout the repository where the infrastructure was managed using code."
          echo "The GitHub action, such as actions/checkout, can be used for the same purpose."

      - name: Get list of running replicaset instance ip addresses from cloudformation codebase
        id: get-list-of-running-replicaset-instance-ip-addresses-from-cloudformation-codebase
        run: |
          echo "Get list of running replicaset instance ip addresses from cloudformation codebase"
          echo "MONGO_CLUSTER_HOSTS=10.4.8.7,10.4.8.22,10.4.8.38" >> $GITHUB_OUTPUT

    outputs:
      MONGO_CLUSTER_HOSTS: ${{ steps.get-list-of-running-replicaset-instance-ip-addresses-from-cloudformation-codebase.outputs.MONGO_CLUSTER_HOSTS }}

  setup-job-environment-via-vpc-runner:
    runs-on: ubuntu-latest
    needs:
      - setup-job-environment

    steps:
      - name: Checkout repo where this GitHub Action is present
        run: |
          echo "Checkout the current repository"
          echo "The GitHub action, such as actions/checkout, can be used for the same purpose."

      - name: Get primary instance ip
        id: get-primary-instance-ip
        run: |
          echo "${{ needs.setup-job-environment.outputs.MONGO_CLUSTER_HOSTS }} was used to connect to replac set"
          echo "Retrieve the primary host IP."
          echo "PRIMARY_HOST=10.4.8.22" >> $GITHUB_OUTPUT

      - name: Get non-arbiter mongo replicaset hosts matrix
        id: get-non-arbiter-mongo-replicaset-hosts-matrix
        run: |
          echo "${{ needs.setup-job-environment.outputs.MONGO_CLUSTER_HOSTS }} was used to connect to replac set"
          echo "Retrieve non-arbiter mongo replicaset hosts matrix."
          echo "MONGO_REPLICASET_HOSTS_MATRIX=10.4.8.7,10.4.8.22,10.4.8.38" >> $GITHUB_OUTPUT

    outputs:
      PRIMARY_HOST: ${{ steps.get-primary-instance-ip.outputs.PRIMARY_HOST }}
      MONGO_REPLICASET_HOSTS_MATRIX: ${{ steps.get-non-arbiter-mongo-replicaset-hosts-matrix.outputs.MONGO_REPLICASET_HOSTS_MATRIX }}

  execute-instance-attributes-update-on-secondary-instances:
    needs:
      - setup-job-environment
      - setup-job-environment-via-vpc-runner

    strategy:
      max-parallel: 1
      matrix:
        InstancePrivateIP: ${{fromJSON(needs.setup-job-environment-via-vpc-runner.outputs.MONGO_REPLICASET_HOSTS_MATRIX)}}

    uses: ./.github/workflows/mongo-update-instance-attributes.yml
    secrets: inherit
    with:
      StackName: ${{ inputs.StackName }}
      InstancePrivateIP: ${{ matrix.InstancePrivateIP }}
      AmiId: ${{ inputs.AmiId }}
      InstanceType: ${{ inputs.InstanceType }}

  pre-flight-validation-for-primary-instance-attributes-update:
    runs-on: ubuntu-latest
    needs:
      - setup-job-environment
      - setup-job-environment-via-vpc-runner
      - execute-instance-attributes-update-on-secondary-instances

    steps:
      - name: Validate that attributes are updated for all secondary hosts
        run: |
          echo "Validate that attributes are updated for all secondary hosts"

      - name: Validate that attributes are not updated for primary
        id: validate-that-attributes-are-not-updated-for-primary
        run: |
          echo "error: Attributes are already updated for primary"
          echo "ARE_PRIMARY_ATTRIBUTES_ALREADY_UPDATED=true" >> $GITHUB_OUTPUT

    outputs:
      ARE_PRIMARY_ATTRIBUTES_ALREADY_UPDATED: ${{ steps.validate-that-attributes-are-not-updated-for-primary.outputs.ARE_PRIMARY_ATTRIBUTES_ALREADY_UPDATED }}

  execute-step-down-primary:
    if: needs.pre-flight-validation-for-primary-instance-attributes-update.outputs.ARE_PRIMARY_ATTRIBUTES_ALREADY_UPDATED == 'false'
    runs-on: ubuntu-latest
    needs:
      - setup-job-environment
      - setup-job-environment-via-vpc-runner
      - execute-instance-attributes-update-on-secondary-instances
      - pre-flight-validation-for-primary-instance-attributes-update

    steps:
      - name: Step down primary
        run: |
          echo "Step down primary"

  execute-instance-attributes-update-on-old-primary-instance:
    if: needs.pre-flight-validation-for-primary-instance-attributes-update.outputs.ARE_PRIMARY_ATTRIBUTES_ALREADY_UPDATED == 'false'
    needs:
      - setup-job-environment
      - setup-job-environment-via-vpc-runner
      - execute-instance-attributes-update-on-secondary-instances
      - pre-flight-validation-for-primary-instance-attributes-update
      - execute-step-down-primary

    strategy:
      max-parallel: 1
      matrix:
        InstancePrivateIP: ${{ needs.setup-job-environment-via-vpc-runner.outputs.PRIMARY_HOST }}


    uses: ./.github/workflows/mongo-update-instance-attributes.yml
    secrets: inherit
    with:
      StackName: ${{ inputs.StackName }}
      InstancePrivateIP: ${{ matrix.InstancePrivateIP }}
      AmiId: ${{ inputs.AmiId }}
      InstanceType: ${{ inputs.InstanceType }}

  execute-set-primary-to-az-a:
    if: needs.pre-flight-validation-for-primary-instance-attributes-update.outputs.ARE_PRIMARY_ATTRIBUTES_ALREADY_UPDATED == 'false'
    runs-on: ubuntu-latest
    needs:
      - setup-job-environment
      - setup-job-environment-via-vpc-runner
      - execute-instance-attributes-update-on-secondary-instances
      - pre-flight-validation-for-primary-instance-attributes-update
      - execute-step-down-primary
      - execute-instance-attributes-update-on-old-primary-instance

    steps:
      - name: Set primary to Az A
        run: |
          echo "Set primary to Az A"

